# Generated by Django 3.1.4 on 2021-05-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('amount', models.TextField()),
                ('billDate', models.TextField()),
                ('recordType', models.TextField(null=True)),
                ('payMethod', models.TextField()),
                ('billType', models.TextField()),
                ('remark', models.TextField(null=True)),
                ('buid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('limitUserID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.TextField()),
                ('time', models.TextField()),
                ('rule', models.TextField()),
                ('back', models.IntegerField()),
                ('ruid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.TextField()),
                ('time', models.TextField()),
                ('amount', models.TextField()),
                ('billType', models.TextField()),
                ('category', models.TextField()),
                ('remark', models.TextField()),
                ('confirm', models.TextField()),
                ('payMethod', models.TextField()),
                ('taskUserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=250)),
                ('avatar', models.TextField()),
                ('nickname', models.CharField(max_length=20)),
                ('lastLogin', models.CharField(max_length=250)),
                ('lastDevice', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=18)),
                ('registrationId', models.CharField(max_length=250)),
            ],
        ),
    ]
